nba_clutch_dbt:
  outputs:
    dev:
      type: duckdb
      path: "{{ env_var('NBA_DB_PATH', '../nba_clutch.duckdb') }}"
      threads: 1

    prod:
      type: duckdb
      path: prod.duckdb
      threads: 4

  target: dev
