version: 2

models:
  - name: player_tier
    columns:
      - name: player_id
        data_tests:
          - unique
          - not_null
      - name: group_tier
        data_tests:
          - accepted_values:
              arguments:
                values: ['Role', 'Star', 'Olympic Gold Medalist']
  - name: player_clutch_performance
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - player_id
              - season
  - name: home_vs_road
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - player_id
              - season
  - name: matchup_analysis
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - player_id
              - season
              - defensive_player_id
  - name: star_player_performance
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
             - player_id
             - season
  - name: player_clutch_playmaking
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - player_id
              - season