CREATE TABLE players (
    id INT PRIMARY KEY,
    full_name VARCHAR(50) NOT NULL
);

CREATE TABLE teams (
    id INT PRIMARY KEY,
    abbreviation CHAR(3),
    full_name VARCHAR(50) NOT NULL
);

CREATE TABLE player_advanced_stats (
    PLAYER_ID INT,
    SEASON VARCHAR(7),
    TEAM_ID INT,
    TEAM_ABBREVIATION CHAR(3),
    AGE INT,
    GP INT,
    MIN DECIMAL,
    OFF_RATING DECIMAL,
    DEF_RATING DECIMAL,
    NET_RATING DECIMAL,
    EFG_PCT DECIMAL,
    TS_PCT DECIMAL,
    USG_PCT DECIMAL,
    PIE DECIMAL,
    POSS INT,
    AST_PCT DECIMAL,
    REB_PCT DECIMAL,
    PRIMARY KEY (PLAYER_ID, SEASON),
    FOREIGN KEY (PLAYER_ID) REFERENCES players (id),
    FOREIGN KEY (TEAM_ID) REFERENCES teams (id)
);

CREATE TABLE player_basic_stats (
    PLAYER_ID INT,
    SEASON VARCHAR(7),
    FGA INT,
    FG3A INT,
    FTA INT,
    PTS INT,
    REB INT,
    AST INT,
    PLUS_MINUS DECIMAL,
    PRIMARY KEY (PLAYER_ID, SEASON),
    FOREIGN KEY (PLAYER_ID) REFERENCES players (id)
);

CREATE TABLE clutch_advanced_stats (
    PLAYER_ID INT,
    SEASON VARCHAR(7),
    GP INT,
    MIN DECIMAL,
    EFG_PCT DECIMAL,
    TS_PCT DECIMAL,
    USG_PCT DECIMAL,
    NET_RATING DECIMAL,
    PIE DECIMAL,
    FGA INT,
    AST_PCT DECIMAL,
    REB_PCT DECIMAL,
    PRIMARY KEY (PLAYER_ID, SEASON),
    FOREIGN KEY (PLAYER_ID) REFERENCES players (id)
);

CREATE TABLE home_clutch_stats (
    PLAYER_ID INT,
    SEASON VARCHAR(7),
    GP INT,
    TS_PCT DECIMAL,
    NET_RATING DECIMAL,
    USG_PCT DECIMAL,
    PRIMARY KEY (PLAYER_ID, SEASON),
    FOREIGN KEY (PLAYER_ID) REFERENCES players (id)
);

CREATE TABLE road_clutch_stats (
    PLAYER_ID INT,
    SEASON VARCHAR(7),
    GP INT,
    TS_PCT DECIMAL,
    NET_RATING DECIMAL,
    USG_PCT DECIMAL,
    PRIMARY KEY (PLAYER_ID, SEASON),
    FOREIGN KEY (PLAYER_ID) REFERENCES players (id)
);

CREATE TABLE primary_defenders_stats (
    OFF_PLAYER_ID INT,
    OFF_PLAYER_NAME VARCHAR(50),
    SEASON VARCHAR(7),
    DEF_PLAYER_ID INT,
    DEF_PLAYER_NAME VARCHAR(50),
    MATCHUP_MIN VARCHAR(10),
    PRIMARY KEY (OFF_PLAYER_ID, SEASON, DEF_PLAYER_ID),
    FOREIGN KEY (OFF_PLAYER_ID) REFERENCES players (id),
    FOREIGN KEY (DEF_PLAYER_ID) REFERENCES players (id)
);

CREATE TABLE player_awards (
    PERSON_ID INT,
    SEASON VARCHAR(7),
    DESCRIPTION VARCHAR(50),
    PRIMARY KEY (PERSON_ID, SEASON, DESCRIPTION),
    FOREIGN KEY (PERSON_ID) REFERENCES players (id)
);

CREATE SEQUENCE clutch_shots_id_seq START 1;

CREATE TABLE clutch_shots (
    shot_id INT PRIMARY KEY DEFAULT nextval('clutch_shots_id_seq'),
    GAME_ID VARCHAR(20),
    PLAYER_ID INT,
    PLAYER_NAME VARCHAR(50),
    SEASON VARCHAR(7),
    PERIOD INT,
    MINUTES_REMAINING INT,
    LOC_X INT,
    LOC_Y INT,
    SHOT_MADE_FLAG INT,
    TEAM_ID INT,
    HTM VARCHAR,
    VTM VARCHAR,
    FOREIGN KEY (PLAYER_ID) REFERENCES players (id)
);

CREATE TABLE team_def_ratings (
    TEAM_ID INT,
    SEASON VARCHAR(7),
    TEAM_NAME VARCHAR(50),
    DEF_RATING DECIMAL,
    PRIMARY KEY (TEAM_ID, SEASON),
    FOREIGN KEY (TEAM_ID) REFERENCES teams (id)
);