version: 2

models:
  - name: player_tier
    columns:
      - name: player_id
        data_tests:
          - unique
          - not_null
      - name: group_tier
        data_tests:
          - accepted_values:
              arguments:
                values: ['Role', 'Star', 'Olympic Gold Medalist']
  - name: player_clutch_performance
    data_tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - player_id
            - season