version: 2

sources:
  - name: raw
    schema: main
    tables:
      - name: players
      - name: teams
      - name: player_advanced_stats
      - name: clutch_advanced_stats
      - name: home_clutch_stats
      - name: road_clutch_stats
      - name: primary_defenders_stats
      - name: player_awards
